blank_issues_enabled: false
contact_links:
  - name: Discord Server
    url: https://discord.gg/yAUmDNb
    about: Join the Discord Server if you have any questions or if you need help (Bot offline, etc.)
  - name: (NEW - Try it!) GitHub Discussions
    url: https://github.com/julianYaman/wikipedia-bot/discussions
    about: Use it for discussing your ideas and for asking questions.